import {
  Landmark,
  Amphora,
  LandPlot,
  ChartArea,
  ShieldCheck,
  PlusCircle,
  Search,
} from "lucide-react";

export const entities = [
  {
    id: 1,
    title: "Ancient Monuments",
    url: "/ancient-monuments",
    icon: Landmark,
    description: "Search for ancient monuments in the system.",
  },
  {
    id: 2,
    title: "Movable Antiquities",
    url: "/movable-antiquities",
    icon: Amphora,
    description: "Search for movable antiquities in the system.",
  },
  {
    id: 3,
    title: "Controlled Areas",
    url: "/controlled-areas",
    icon: ShieldCheck,
    description: "Search for controlled areas in the system.",
  },
  {
    id: 4,
    title: "Areas Under Temporary Requisition",
    url: "/areas-under-temp-requisition",
    icon: LandPlot,
    description: "Search for areas under temporary requisition in the system.",
  },
  {
    id: 5,
    title: "Surveyed Areas",
    url: "/surveyed-areas",
    icon: ChartArea,
    description: "Search for surveyed areas in the system.",
  },
];

export const ancientMonuments = [
  {
    id: 1,
    url: "/ancient-monuments/1",
    name: "The castle of Limassol",
    district: "Lemesos",
    town: "LEMESOS",
    recordedBy: "M.Kouali",
  },
  {
    id: 2,
    url: "/ancient-monuments/2",
    name: "The castle of Pafos",
    district: "Pafos",
    town: "PAFOS",
    recordedBy: "N.Zoros",
  },
  {
    id: 3,
    url: "/ancient-monuments/3",
    name: "The castle of Larnaca",
    district: "Larnaka",
    town: "LARNAKA",
    recordedBy: "A.Antonio",
  },
  {
    id: 4,
    url: "/ancient-monuments/4",
    name: "The castle of Ammochostos",
    district: "Ammochostos",
    town: "AMMOCHOSTOS",
    recordedBy: "M.Kouali",
  },
  {
    id: 5,
    url: "/ancient-monuments/5",
    name: "The castle of Keryneia",
    district: "Keryneia",
    town: "KERYNEIA",
    recordedBy: "N.Zoros",
  },
  {
    id: 6,
    url: "/ancient-monuments/6",
    name: "The castle of Lefkosia",
    district: "Lefkosia",
    town: "LEFKOSIA",
    recordedBy: "A.Antonio",
  },
  {
    id: 7,
    url: "/ancient-monuments/7",
    name: "The ancient theater of Kourion",
    district: "Lemesos",
    town: "KOURION",
    recordedBy: "M.Kouali",
  },
  {
    id: 8,
    url: "/ancient-monuments/8",
    name: "The ancient city of Salamis",
    district: "Ammochostos",
    town: "SALAMIS",
    recordedBy: "N.Zoros",
  },
  {
    id: 9,
    url: "/ancient-monuments/9",
    name: "The ancient city of Amathus",
    district: "Lemesos",
    town: "AMATHUS",
    recordedBy: "A.Antonio",
  },
  {
    id: 10,
    url: "/ancient-monuments/10",
    name: "The ancient city of Pafos",
    district: "Pafos",
    town: "PAFOS",
    recordedBy: "M.Kouali",
  },
  {
    id: 11,
    url: "/ancient-monuments/11",
    name: "The ancient city of Kition",
    district: "Larnaka",
    town: "KITION",
    recordedBy: "N.Zoros",
  },
];

export const movableAntiquities = [
  {
    id: 1,
    url: "/movable-antiquities/1",
    name: "Ancient Vase",
    district: "Keryneia",
    town: "AGIOS ERMOLAOS",
    recordedBy: "N.Mikrakis",
  },
  {
    id: 2,
    url: "/movable-antiquities/2",
    name: "Ancient Coin",
    district: "Lemesos",
    town: "LEFKOSIA",
    recordedBy: "A.Antonio",
  },
  {
    id: 3,
    url: "/movable-antiquities/3",
    name: "Ancient Statue",
    district: "Pafos",
    town: "PAFOS",
    recordedBy: "M.Kouali",
  },
  {
    id: 4,
    url: "/movable-antiquities/4",
    name: "Ancient Jewelry",
    district: "Larnaka",
    town: "LARNAKA",
    recordedBy: "N.Zoros",
  },
  {
    id: 5,
    url: "/movable-antiquities/5",
    name: "Ancient Tool",
    district: "Ammochostos",
    town: "AMMOCHOSTOS",
    recordedBy: "A.Antonio",
  },
  {
    id: 6,
    url: "/movable-antiquities/6",
    name: "Ancient Weapon",
    district: "Pafos",
    town: "MESANA",
    recordedBy: "N.Mikrakis",
  },
];

export const controlledAreas = [
  {
    id: 1,
    url: "/controlled-areas/1",
    name: "aaaaaaa",
    district: "Keryneia",
    town: "AGIOS ERMOLAOS",
    recordedBy: "N.Mikrakis",
  },
  {
    id: 2,
    url: "/controlled-areas/2",
    name: "aaaaaaa",
    district: "Keryneia",
    town: "AGIOS ERMOLAOS",
    recordedBy: "N.Mikrakis",
  },
  {
    id: 3,
    url: "/controlled-areas/3",
    name: "aaaaaaa",
    district: "Keryneia",
    town: "AGIOS ERMOLAOS",
    recordedBy: "N.Mikrakis",
  },
  {
    id: 4,
    name: "aaaaaaa",
    url: "/controlled-areas/4",
    district: "Keryneia",
    town: "AGIOS ERMOLAOS",
    recordedBy: "N.Mikrakis",
  },
  {
    id: 5,
    url: "/controlled-areas/5",
    name: "aaaaaaa",
    district: "Keryneia",
    town: "AGIOS ERMOLAOS",
    recordedBy: "N.Mikrakis",
  },
];

export const areasUnderTempReq = [
  {
    id: 1,
    url: "/areas-under-temp-requisition/1",
    name: "aaaaaaa",
    district: "Keryneia",
    town: "AGIOS ERMOLAOS",
    recordedBy: "N.Mikrakis",
  },
  {
    id: 2,
    url: "/areas-under-temp-requisition/2",
    name: "aaaaaaa",
    district: "Keryneia",
    town: "AGIOS ERMOLAOS",
    recordedBy: "N.Mikrakis",
  },
  {
    id: 3,
    url: "/areas-under-temp-requisition/3",
    name: "aaaaaaa",
    district: "Keryneia",
    town: "AGIOS ERMOLAOS",
    recordedBy: "N.Mikrakis",
  },
  {
    id: 4,
    url: "/areas-under-temp-requisition/4",
    name: "aaaaaaa",
    district: "Keryneia",
    town: "AGIOS ERMOLAOS",
    recordedBy: "N.Mikrakis",
  },
  {
    id: 5,
    url: "/areas-under-temp-requisition/5",
    name: "aaaaaaa",
    district: "Keryneia",
    town: "AGIOS ERMOLAOS",
    recordedBy: "N.Mikrakis",
  },
  {
    id: 6,
    url: "/areas-under-temp-requisition/6",
    name: "aaaaaaa",
    district: "Keryneia",
    town: "AGIOS ERMOLAOS",
    recordedBy: "N.Mikrakis",
  },
];

export const surveyedAreas = [
  {
    id: 1,
    url: "/surveyed-areas/1",
    name: "aaaaaaa",
    district: "Keryneia",
    town: "AGIOS ERMOLAOS",
    recordedBy: "N.Mikrakis",
  },
  {
    id: 2,
    url: "/surveyed-areas/2",
    name: "aaaaaaa",
    district: "Keryneia",
    town: "AGIOS ERMOLAOS",
    recordedBy: "N.Mikrakis",
  },
  {
    id: 3,
    url: "/surveyed-areas/3",
    name: "aaaaaaa",
    district: "Keryneia",
    town: "AGIOS ERMOLAOS",
    recordedBy: "N.Mikrakis",
  },
  {
    id: 4,
    url: "/surveyed-areas/4",
    name: "aaaaaaa",
    district: "Keryneia",
    town: "AGIOS ERMOLAOS",
    recordedBy: "N.Mikrakis",
  },
  {
    id: 5,
    url: "/surveyed-areas/5",
    name: "aaaaaaa",
    district: "Keryneia",
    town: "AGIOS ERMOLAOS",
    recordedBy: "N.Mikrakis",
  },
  {
    id: 6,
    url: "/surveyed-areas/6",
    name: "aaaaaaa",
    district: "Keryneia",
    town: "AGIOS ERMOLAOS",
    recordedBy: "N.Mikrakis",
  },
  {
    id: 7,
    url: "/surveyed-areas/7",
    name: "aaaaaaa",
    district: "Keryneia",
    town: "AGIOS ERMOLAOS",
    recordedBy: "N.Mikrakis",
  },
];

export const actions = [
  {
    icon: PlusCircle,
    name: "Add",
    helper: "add",
    description: "Add new data to the system.",
  },
  // {
  //   icon: Pencil,
  //   name: "Edit",
  //   helper:"edit",
  //   description: "Edit existing data in the system.",
  // },
  {
    icon: Search,
    name: "Search",
    helper: "search",
    description: "Search through the data available in the system.",
  },
  // {
  //   icon: RefreshCw,
  //   name: "Sync Check",
  //   helper:"",
  //   description:
  //     "Sync spatial data with external sources and make inconsistent check.",
  // },
];
